Source/QBox.Web/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using QBox.Api.Client;
using QBox.Logging;
using QBox.Web.Models;

namespace QBox.Web.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IQBoxClient apiClient;

        public CategoryController(IQBoxClient apiClient)
        {
            this.apiClient = apiClient;
        }

        public ActionResult Index()
        {
            var allCategories = apiClient.GetCategories().Result;
            var model = new QuizCategoriesViewModel
            {
                Categories = allCategories.Select(
                    c => new QuizCategoryViewModel() {Id = c.Id, Name = c.Name, Description = c.Description}).ToList()
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Start(FormCollection form)
        {
            if (form.Count != 1)
            {
                return RedirectToAction("Index");
            }

            string selectedCategory = Convert.ToString(form[0]);
            Logger.Event(selectedCategory);

            return RedirectToAction("Index", "Question", new {category=selectedCategory});
        }

        [HttpPost]
        public async Task<ActionResult> Random()
        {
            var allCategories = await apiClient.GetCategories();
            var selectedCategory = allCategories[new Random().Next(0, allCategories.Count - 1)].Name;
            Logger.Event("randomCategory");
            return RedirectToAction("Index", "Question", new { category = selectedCategory });
        }

    }

}

Source/QBox.Web/Views/Category/Index.cshtml
@model QBox.Web.Models.QuizCategoriesViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row row-centered">
    <div class="col-md-8">
        <div class="well">
            <h2>Let's play a new Quiz Game!</h2>
        </div>
        <div class="row">
            <div class="col-md-8">
                <h4>Start by selecting a category:</h4>
                <div class="form-group">
                    @using (Html.BeginForm("Start", "Category", FormMethod.Post, new { role = "form" }))
                    {
                        <div class="list-group list-categories">

                            @foreach (var c in Model.Categories)
                            {
                                <div class="list-group-item">
                                    <button type="submit" class="btn btn-lg btn-info btn-category" value="@c.Name" name="@c.Id">@c.Name</button>
                                </div>
                            }
                        </div>
                    }
                </div>
            </div>

            <div class="col-md-4">
                <h4>Or, select one for me!</h4>
                <div class="form-group">
                    @using (Html.BeginForm("Random", "Category", FormMethod.Post, new { role = "form" }))
                    {
                        <button type="submit" class="btn">
                            <img src="~/Content/Images/selectrandom.jpeg" class="img img-circle" width="128px">
                        </button>
                    }
                </div>

            </div>
        </div>

    </div>
    <div class="col-md-4">
        <div class="col-md4">
            <img src="~/Content/Images/small-logo.jpg" class="img img-circle">
        </div>
    </div>
</div>